package heim:api@1.0.0;

interface account {
  use types.{ auth-response };
  account-login: func(code: string, login-provider: string) -> auth-response;
}

/// This is the Ray Account API
world api {
  export account;
}
